core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from core.shirt import views

urlpatterns = [
    path('shirt/admin', admin.site.urls),
    path('', RedirectView.as_view(url='/shirt'), name='shirt-root'),
    path('shirt', views.ShirtListView.as_view(), name='shirt-list'),
    path('shirt/all', views.FullShirtView.as_view(), name='full-shirt'),
    path('shirt/print', views.PrintTypeView.as_view(), name='print-type'),
    path('shirt/print/<slug:print>', views.PrintShirtView.as_view(), name='print-shirt'),
    path('shirt/brand', views.BrandView.as_view(), name='brand'),   
    path('shirt/brand/<slug:brand>', views.BrandShirtView.as_view(), name='brand-shirt'),   
    path('shirt/size', views.SizeView.as_view(), name='size'),   
    path('shirt/size/<slug:size>', views.SizeShirtView.as_view(), name='size-shirt'),   
    path('shirt/item/<slug:shirt>', views.ShirtDetailView.as_view(), name='shirt-detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shirt/models.py
from django.db import models
from django.utils.text import slugify
from versatileimagefield.fields import VersatileImageField, PPOIField

# Create your models here.

def upload_media(instance, filename):
    return 'images/{0}/{1}'.format(instance.shirt.id, filename)


class Brand(models.Model):
    code = models.SlugField(max_length=200, blank=True, editable=False, unique=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.code = slugify(self.name)
        super(Brand, self).save(*args, **kwargs)


class PrintType(models.Model):
    code = models.SlugField(max_length=200, blank=True, editable=False, unique=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.code = slugify(self.name)
        super(PrintType, self).save(*args, **kwargs)


class Shirt(models.Model):
    code = models.SlugField(max_length=200, blank=True, editable=False, unique=True)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=2000, null=True, blank=True)
    print_type = models.ManyToManyField(PrintType)
    shirt_brand = models.ManyToManyField(Brand)
    featured = models.BooleanField(default=False)
    best_seller = models.BooleanField(default=False)
    price = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def is_featured(self):
        return self.featured

    def is_best_seller(self):
        return self.best_seller

    def get_available_sizes(self):
        text = ''
        for inventory in self.inventory.all():
            if inventory.stock > 0:
                if text == '':
                    text = inventory.size.name
                else:
                    text = ', '.join([text, inventory.size.name])
        return text

    def get_print_type(self):
        return ', '.join([ print_type.name for print_type in self.print_type.all() ])

    def get_shirt_brand(self):
        return ', '.join([ shirt_brand.name for shirt_brand in self.shirt_brand.all() ])

    def save(self, *args, **kwargs):
        self.code = slugify(self.name)
        super(Shirt, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name"]


class Image(models.Model):
    shirt = models.ForeignKey(Shirt, related_name='image', on_delete=models.CASCADE)
    image = VersatileImageField(
        'Image',
        upload_to=upload_media,
        ppoi_field='center_point')
    center_point = PPOIField('Image Center Point of Interest')
    weight = models.PositiveSmallIntegerField(default=9)

    def __str__(self):
        return '{0} - {1}'.format(self.shirt.name, self.weight)

    class Meta:
        ordering = ["weight", "shirt"]


class Size(models.Model):
    code = models.SlugField(max_length=200, blank=True, editable=False, unique=True)
    name = models.CharField(max_length=200)
    size_guide = models.CharField(max_length=200, null=True, blank=True)
    weight = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.code = slugify(self.name)
        super(Size, self).save(*args, **kwargs)

    class Meta:
        unique_together = ('code', 'weight')
        ordering = ['weight']


class Inventory(models.Model):
    shirt = models.ForeignKey(Shirt, related_name='inventory', on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    stock = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return '{0} - {1}'.format(self.shirt.name, self.size.name)

    class Meta:
        unique_together = ('shirt', 'size')
        ordering = ['-stock','shirt', 'size']


class Gallery(models.Model):
    shirt = models.ForeignKey(Shirt, related_name='gallery', on_delete=models.CASCADE)
    image = VersatileImageField(
        'Image',
        upload_to=upload_media,
        ppoi_field='center_point')
    center_point = PPOIField('Image Center Point of Interest')
    credit = models.CharField(max_length=200, null=True, blank=True)
    weight = models.PositiveSmallIntegerField(default=9)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{0} - {1}'.format(self.shirt.name, self.image.name)

    class Meta:
        ordering = ['weight', 'updated_at']

core/shirt/views.py
from django.shortcuts import render
from django.views import generic
from django.http import Http404

#REST Related
from rest_framework import viewsets, pagination
from django_filters import rest_framework as filters
from .serializers import ShirtSerializer

# Create your views here.

from .models import Shirt, Image, PrintType, Brand, Size, Inventory


class ShirtListView(generic.ListView):
    model = Shirt
    paginate_by = 6


class FullShirtView(generic.ListView):
    model = Shirt


class ShirtDetailView(generic.DetailView):
    model = Shirt

    def get_object(self):
        try:
            return Shirt.objects.get(code=self.kwargs['shirt'])
        except Shirt.DoesNotExist:
            raise Http404()


class PrintShirtView(generic.ListView):
    model = Shirt

    def get_queryset(self):
        try:
            return Shirt.objects.filter(print_type__code__exact=self.kwargs['print'])
        except Shirt.DoesNotExist:
            raise Http404()


class PrintTypeView(generic.ListView):
    model = PrintType


class BrandShirtView(generic.ListView):
    model = Shirt

    def get_queryset(self):
        try:
            return Shirt.objects.filter(shirt_brand__code__exact=self.kwargs['brand'])
        except Shirt.DoesNotExist:
            raise Http404()


class BrandView(generic.ListView):
    model = Brand


class SizeShirtView(generic.ListView):
    model = Shirt

    def get_queryset(self):
        try:
            return Shirt.objects.filter(inventory__size__code__exact=self.kwargs['size'], inventory__stock__gt=0)
        except Shirt.DoesNotExist:
            raise Http404()


class SizeView(generic.ListView):
    model = Size


#REST Related
class ShirtFilter(filters.FilterSet):
	name = filters.CharFilter(field_name='name', lookup_expr='icontains')

	class Meta:
		model = Shirt
		fields = ['name']


class ShirtPagination(pagination.PageNumberPagination):
	page_size = 20
	page_size_query_param = 'page_size'
	max_page_size = 100


class ShirtViewSet(viewsets.ReadOnlyModelViewSet):
	serializer_class = ShirtSerializer
	filterset_class = ShirtFilter
	pagination_class = ShirtPagination
	queryset = Shirt.objects.all()



###################### DEV SECTION =============================

class DevShirtDetailView(generic.DetailView):
    model = Shirt
    template_name = "shirt/shirt_detail_v2.html"

    def get_object(self):
        try:
            return Shirt.objects.get(code=self.kwargs['shirt'])
        except Shirt.DoesNotExist:
            raise Http404()

class DevShirtListView(generic.ListView):
    model = Shirt
    paginate_by = 6
    template_name = "shirt/shirt_list_v2.html"

class DevFullShirtView(generic.ListView):
    model = Shirt
    template_name = "shirt/shirt_list_v2.html"

core/shirt/templates/base-v2.html
<!doctype html>
<html ⚡>
<head>
    {% load static %}
    <!-- Required for AMP -->
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
    <script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
    <script async custom-element="amp-fit-text" src="https://cdn.ampproject.org/v0/amp-fit-text-0.1.js"></script>

    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    
    {% include "base-v2-css.html" %}
    
    <!-- Inline amp-boilerplate required as well -->
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

    {% block title %} {% endblock %}
    {% block meta %} {% endblock %}

</head>

<body>

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->

<div class="sidebar" id="sidebar">
    <div class="sidebar-item">
      <p>moe.ph &middot; cute and depressed</p>
    </div>
  
    <nav class="sidebar-nav">
      <a class="sidebar-nav-item" href="/shirt/">Home</a>
  
      <a class="sidebar-nav-item" href="/shirt/all">Full Catalog</a>
      <a class="sidebar-nav-item" href="/shirt/print/">Browse by Print Type</a>
      <a class="sidebar-nav-item" href="/shirt/brand/">Browse by Shirt Brand</a>
      <a class="sidebar-nav-item" href="/shirt/size/">Browse by Available Sizes</a>
  
      <span class="sidebar-nav-item">Social Media Links</span>
  
      <a class="sidebar-nav-item" href="https://facebook.com/be.moe.ph">Facebook Page</a>
      <a class="sidebar-nav-item" href="https://m.me/be.moe.ph">Messenger Link</a>
      <a class="sidebar-nav-item" href="https://github.com/ZeroExistence">GitHub Repository</a>
  
      <span class="sidebar-nav-item">Currently v site.version</span>
    </nav>
  
    <div class="sidebar-item">
      <p>
        &copy; moe.ph. All rights reserved.<br> Made with Django, Lanyon, and basscss.
      </p>
    </div>
  </div>
  
  <div class="wrap">
      <div class="masthead">
          <div class="container">
              <h3 class="masthead-title">
              <a href="/shirt/" title="Home">moe.ph</a>
              <small>cute and depressed</small>
              </h3>
          </div>
      </div>
  
  {% block content %} {% endblock %}
  
  </div>
    <label for="sidebar-checkbox" class="sidebar-toggle"></label>
    </body>
</html>

core/shirt/templates/base.html
<!doctype html>
<html ⚡>
<head>
    {% load static %}
    <!-- Required for AMP -->
    <meta charset="utf-8">
    <script async src="https://cdn.ampproject.org/v0.js"></script>
    <script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
    <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
    <script async custom-element="amp-selector" src="https://cdn.ampproject.org/v0/amp-selector-0.1.js"></script>
    <script async custom-element="amp-fit-text" src="https://cdn.ampproject.org/v0/amp-fit-text-0.1.js"></script>

    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">

    {% include "base-css.html" %}

    <!-- Inline amp-boilerplate required as well -->
    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

    {% block title %} {% endblock %}
    {% block meta %} {% endblock %}

</head>

<body>

    <!-- Target for toggling the sidebar `.sidebar-checkbox` is for regular
     styles, `#sidebar-checkbox` for behavior. -->
<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<!-- Toggleable sidebar -->

<div class="sidebar" id="sidebar">
    <div class="sidebar-item">
      <p>moe.ph</p>
    </div>

    <nav class="sidebar-nav">
      <a class="sidebar-nav-item" href="/shirt">Home</a>

      <a class="sidebar-nav-item" href="/shirt/all">Full Catalog</a>
      <a class="sidebar-nav-item" href="/shirt/print">Browse by Print Type</a>
      <a class="sidebar-nav-item" href="/shirt/brand">Browse by Shirt Brand</a>
      <a class="sidebar-nav-item" href="/shirt/size">Browse by Available Sizes</a>

      <span class="sidebar-nav-item">Social Media Links</span>

      <a class="sidebar-nav-item" href="https://facebook.com/be.moe.ph">Facebook Page</a>
      <a class="sidebar-nav-item" href="https://m.me/be.moe.ph">Messenger Link</a>
      <a class="sidebar-nav-item" href="https://github.com/ZeroExistence">GitHub Repository</a>

      <span class="sidebar-nav-item">Currently v site.version</span>
    </nav>

    <div class="sidebar-item">
      <p>
        &copy; moe.ph. All rights reserved.<br> Made with Django, Lanyon, and basscss.
      </p>
    </div>
  </div>

  <div class="wrap">
      <div class="masthead">
          <div class="container">
              <h3 class="masthead-title">
              <a href="/shirt/" title="Home">moe.ph</a>
              <small>&middot; cute and depressed</small>
              </h3>
          </div>
      </div>

  {% block content %} {% endblock %}

  </div>
    <label for="sidebar-checkbox" class="sidebar-toggle"></label>
    </body>
</html>

core/shirt/templates/shirt/brand_list.html
{% extends "base.html" %}


{% block title %}
<link rel="canonical" href="{{ request.build_absolute_uri }}">
<title>
moe.ph &middot; cute and depressed
</title>
{% endblock %}


{% block meta %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="moe.ph &middot; cute and depressed" />
<meta property="og:description" content="Browse by Brand Type" />
<meta property="og:image" content="{{ brand.shirt_set.first.image.first.image.crop.1200x628 }}" />

<meta name="moe.ph &middot; cute and depressed" content="cute and depressed">
{% endblock %}


{% block content %}
<div class="container">
<div class="clearfix">
{% for brand in brand_list %}
<div class="page sm-col sm-col-6">
    <div>
    <a href="{% url 'brand-shirt' brand.code %}">
        <amp-img src="{{ brand.shirt_set.first.image.first.image.thumbnail.600x600.url }}" alt="{{ brand.name }}" layout="responsive" width="600" height="600"></amp-img>
        <amp-fit-text layout="responsive" width="500" height="50">{{ brand.name }}</amp-fit-text>
    </a>
    </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

core/shirt/templates/shirt/printtype_list.html
{% extends "base.html" %}


{% block title %}
<link rel="canonical" href="{{ request.build_absolute_uri }}">
<title>
moe.ph &middot; cute and depressed
</title>
{% endblock %}


{% block meta %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="moe.ph &middot; cute and depressed" />
<meta property="og:description" content="Browse by Print Type" />
<meta property="og:image" content="{{ printtype.shirt_set.first.image.first.image.crop.1200x628 }}" />

<meta name="moe.ph &middot; cute and depressed" content="cute and depressed">
{% endblock %}


{% block content %}
<div class="container">
<div class="clearfix">
{% for printtype in printtype_list %}
<div class="page sm-col sm-col-6">
    <div>
    <a href="{% url 'print-shirt' printtype.code %}">
        <amp-img src="{{ printtype.shirt_set.first.image.first.image.thumbnail.600x600.url }}" alt="{{ printtype.name }}" layout="responsive" width="600" height="600"></amp-img>
        <amp-fit-text layout="responsive" width="500" height="50">{{ printtype.name }}</amp-fit-text>
    </a>
    </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}

core/shirt/templates/shirt/shirt_detail.html
{% extends "base.html" %}


{% block title %}
<link rel="canonical" href="{{ request.build_absolute_uri }}">
<title>
{{ shirt.name }} &middot; moe.ph
</title>
{% endblock %}


{% block meta %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ shirt.name }} &middot; moe.ph" />
<meta property="og:description" content="{{ shirt.description | truncatechars:190 }}" />
<meta property="og:image" content="{{ shirt.image.first.image.crop.1200x628 }}" />

<meta name="{{ shirt.name }} &middot; moe.ph" content="{{ shirt.description }}" />
{% endblock %}


{% block content %}
<div class="container">
<div>
  <amp-carousel id="carouselWithPreview"
    width="500"
    height="500"
    layout="responsive"
    type="slides"
    on="slideChange:carouselWithPreviewSelector.toggle(index=event.index, value=true)">
    <amp-img src="{{ shirt.image.first.image.thumbnail.1028x1028.url }}"
      layout="fill"
      alt="a sample image"></amp-img>
    <amp-img src="{{ shirt.image.first.image.zoom_75.1028x1028.url }}"
      layout="fill"
      alt="a sample image"></amp-img>
    <amp-img src="{{ shirt.image.first.image.zoom_50.1028x1028.url }}"
      layout="fill"
      alt="a sample image"></amp-img>
  </amp-carousel>
  <amp-selector id="carouselWithPreviewSelector"
    class="carousel-preview"
    on="select:carouselWithPreview.goToSlide(index=event.targetOption)"
    layout="container">
    <amp-img option="0"
      selected
      src="{{ shirt.image.first.image.thumbnail.60x60.url }}"
      width="60"
      height="60"
      alt="a sample image"></amp-img>
    <amp-img option="1"
      src="{{ shirt.image.first.image.zoom_75.60x60.url }}"
      width="60"
      height="60"
      alt="a sample image"></amp-img>
    <amp-img option="2"
      src="{{ shirt.image.first.image.zoom_50.60x60.url }}"
      width="60"
      height="60"
      alt="a sample image"></amp-img>
  </amp-selector>
</div>
<br>
<span class="post-date">Last Updated: {{ shirt.updated_at.date }}</span>
<h1 class="post-title">{{ shirt.name }}</h1>
<h3>{{ shirt.description }}</h3>
<hr>
<h3>Price: <small>P{{ shirt.price }}</small></h3>
<h3>Available Sizes: <small>{{ shirt.get_available_sizes }}</small></h3>
<h3>Print Type: <small>{{ shirt.get_print_type }}</small></h3>
<h3>Brand: <small>{{ shirt.get_shirt_brand }}</small></h3>
<h3>Shipping Fee: <br/><small>Luzon: PHP 85 / Manila: PHP 95 / Visayas: PHP 100 / Mindanao: PHP 105</small></h3>
<h3 class="center">To order, just contact us in our Facebook Page <a href="https://facebook.com/be.moe.ph">moe.ph</a></h3>

{% if shirt.gallery.all %}
<hr>
<h2>Customer Submitted Gallery</h2>
<amp-carousel class="carousel-caption" layout="fixed-height" height="640" type="slides" id="GalleryCarousel" on="slideChange:GalleryCarouselSelector.toggle(index=event.index, value=true),carouselPreview.goToSlide(index=event.index)">
{% for gallery in shirt.gallery.all %}
<div class="slide">
<amp-img src="{{ gallery.image.thumbnail.720x600.url }}" alt="{{ gallery.credit }}" layout="fill" width="600" height="600" attribution="{{ gallery.credit }}"></amp-img>
{% if gallery.credit is not None %}
<div class="caption">CREDIT: {{ gallery.credit | safe }} </div>
{% endif %}
</div>
{% endfor %}
</amp-carousel>
<amp-selector id="GalleryCarouselSelector"
    on="select:GalleryCarousel.goToSlide(index=event.targetOption)"
    layout="container">
    <amp-carousel id="carouselPreview" class="carousel-preview" height="72" layout="fixed-height" type="carousel">
    {% for gallery in shirt.gallery.all %}
    <amp-img option="{{ forloop.counter0 }}"
      {% if forloop.counter0 == 0 %} selected {% endif %}
      src="{{ gallery.image.crop.60x60.url }}"
      width="60"
      height="60"
      alt="a sample image"></amp-img>
    {% endfor %}
    </amp-carousel>
  </amp-selector>
{% endif %}

</div>

{% endblock %}

core/shirt/templates/shirt/shirt_list.html
{% extends "base.html" %}


{% block title %}
<link rel="canonical" href="{{ request.build_absolute_uri }}">
<title>
moe.ph &middot; cute and depressed
</title>
{% endblock %}


{% block meta %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="moe.ph &middot; cute and depressed" />
<meta property="og:description" content="cute and depressed" />
<meta property="og:image" content="{{ shirt_list.first.image.first.image.crop.1200x628 }}" />

<meta name="moe.ph &middot; cute and depressed" content="cute and depressed">
{% endblock %}


{% block content %}

<div class="container">
<div class="clearfix">
{% for shirt in shirt_list %}
<div class="page sm-col sm-col-6">
    <div>
    <a href="{% url 'shirt-detail' shirt.code %}">
        <amp-img src="{{ shirt.image.first.image.thumbnail.600x600.url }}" alt="{{ shirt.name }}" layout="responsive" width="600" height="600"></amp-img>
        <amp-fit-text layout="responsive" width="500" height="50">{{ shirt.name }}</amp-fit-text>
    </a>
    </div>
</div>
{% endfor %}
</div>
</div>

{% if is_paginated %}
<div class="container">
<div class="clearfix">
<div class="center">
{% if page_obj.has_previous %}
<a class="btn btn-outline" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
<span>Current Page: {{ page_obj.number }}</span>
{% if page_obj.has_next %}
<a class="btn btn-outline" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% endif %}

</div>
</div>
{% endif %}

{% endblock %}

core/shirt/templates/shirt/shirt_list_v2.html
{% extends "base-v2.html" %}


{% block title %}
<title>
moe.ph &middot; cute and depressed
</title>
{% endblock %}


{% block meta %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="moe.ph &middot; cute and depressed" />
<meta property="og:description" content="cute and depressed" />
<meta property="og:image" content="{{ shirt_list.first.image.first.image.crop.1200x628 }}" />

<meta name="moe.ph &middot; cute and depressed" content="cute and depressed">
{% endblock %}


{% block content %}

<div class="container">
<div class="clearfix">
{% for shirt in shirt_list %}
<div class="page sm-col sm-col-6">
    <div class="slide">
    <a href="{% url 'dev-shirt-detail' shirt.code %}">
        <amp-img src="{{ shirt.image.first.image.thumbnail.600x600.url }}" alt="{{ shirt.name }}" layout="responsive" width="600" height="600"></amp-img>
        <amp-fit-text layout="responsive" width="500" height="50">{{ shirt.name }}</amp-fit-text>
    </a>
    </div>
</div>
{% endfor %} 
</div>
</div>

{% if is_paginated %}
<div class="container">
<div class="clearfix">
<div class="center">
{% if page_obj.has_previous %}
<a class="btn btn-outline" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
<span>Current Page: {{ page_obj.number }}</span>
{% if page_obj.has_next %}
<a class="btn btn-outline" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% endif %}

</div>
</div>
{% endif %}

{% endblock %}

core/shirt/templates/shirt/size_list.html
{% extends "base.html" %}


{% block title %}
<link rel="canonical" href="{{ request.build_absolute_uri }}">
<title>
moe.ph &middot; cute and depressed
</title>
{% endblock %}


{% block meta %}
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="moe.ph &middot; cute and depressed" />
<meta property="og:description" content="Browse by Available Sizes" />
<meta property="og:image" content="{{ size.inventory_set.last.shirt.image.first.image.crop.1200x628 }}" />

<meta name="moe.ph &middot; cute and depressed" content="cute and depressed">
{% endblock %}


{% block content %}
<div class="container">
<div class="clearfix">
{% for size in size_list %}
<div class="page sm-col sm-col-6">
    <div>
    <a href="{% url 'size-shirt' size.code %}">
        <amp-img src="{{ size.inventory_set.last.shirt.image.first.image.thumbnail.600x600.url }}" alt="{{ size.name }}" layout="responsive" width="600" height="600"></amp-img>
        <amp-fit-text layout="responsive" width="500" height="50">{{ size.name }}</amp-fit-text>
    </a>
    </div>
</div>
{% endfor %}
</div>
</div>
{% endblock %}